language: go
services:
- docker
go:
- 1.12.x
script:
- make
deploy:
  - provider: releases
    api_key:
      secure: WUWG5LYhk+/dC2KnNIrt4Iviulz7tPru5gZY5ezBOBWVRZWgVY3u6dcz4bYQ6PzUdIll6Zys/H0MMRsyIKNChXtDRuwFNPEoUNofb18DOSr08YB8dJ9137aL8X4qqiAbVYVOqs1iLBUJjLjehrqxcuFD5EBVTK71jfhqY6YuUSyhIeaLixyLpc5eHsmjBSadlCrsQ/bwV9TpTJdUIthEjOtJ69vImNMcL0BwISpF4pVJ3dRhmQ/Zy99kGUlsn35jZotb2ZrsMIz8Yh09rkEyYEbMZ/ey8VYxhfb9plJnp/fB/k74I2vH9DdIg6vD2jBpSaWIoniDMRt1lcPeBRCwKo1F4wCDZfx5HPq0e3XmgUkkcB3In7/C2g5aeQ5AE9TmVeaXo9Luv9I5D20s/6IpI1S/u6qErkF8hcuwx9l3h1cPbb5yO3yAGtBKvUnpGK1BzGmOANq1mXU4CC3QEMejsg+wuUmrK34RVxszNcAZUqhEfPtf/ebzJFLZPkx+vpe5haIueid5Mcr3ZEEsFdCGxbNp6F+UFY7S3spoq8Mi4/o8nh7omfZroRcDXRwQZMRLDBMXqSm6HyCDRIDG3O5b8Hwa/Ozu1+MkLJMS9LNwxnh6Vmysy8RTDcoUsgB3P3eNojTGBapKmxR4nI3SVdO92y47Qm1hR68NTpH6KYc3nws=
    skip_cleanup: true
    file:
    - "build/twistlock-controller-linux-x64"
    - "build/twistlock-controller-darwin-x64"
    - "build/twistlock-controller-win-x64.exe"
    on:
      tags: true
  - provider: script
    script: bash ./scripts/docker-deploy.sh
    on:
      tags: true
